export interface Friend{
  id:string
  name:string
  icon:string
}

export const friendNew: Friend = {id:"0",name:"ccc", icon: ""};

export const friendList:Array<Friend> = [
  {id:"1",name:"跳转",icon:"http://112.74.183.138:8889/imgs/06.jpg"},
  {id:"2",name:"网络请求",icon:"1.png"},
  {id:"3",name:"加载图片",icon:"1.png"},
  {id:"4",name:"aaa",icon:"1.png"},
  {id:"5",name:"sss",icon:"1.png"},
  {id:"6",name:"aaa",icon:"1.png"},
  {id:"7",name:"aaa",icon:"1.png"},
  {id:"8",name:"aaa",icon:"1.png"},
  {id:"9",name:"sss",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"1",name:"sss",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"1",name:"sss",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"},
  {id:"2",name:"aaa",icon:"1.png"}

]

